USE master;
GO

-- 1. XÓA DB CŨ NẾU TỒN TẠI
IF EXISTS (SELECT name FROM sys.databases WHERE name = N'PetCareX')
BEGIN
    ALTER DATABASE PetCareX SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE PetCareX;
END
GO

-- 2. TẠO DATABASE MỚI
CREATE DATABASE PetCareX;
GO
USE PetCareX;
GO

-----------------------------------------------------------
-- PHẦN 1: CÁC BẢNG DANH MỤC (MASTER DATA)
-----------------------------------------------------------

CREATE TABLE HANG_THANH_VIEN (
    MaHang INT IDENTITY(1,1) PRIMARY KEY,
    TenHang NVARCHAR(50) NOT NULL,
    ChiTieuGiuHang DECIMAL(18,0) DEFAULT 0,
    ChiTieuDatHang DECIMAL(18,0) DEFAULT 0
);

CREATE TABLE CHI_NHANH (
    MaCN INT IDENTITY(1,1) PRIMARY KEY,
    TenCN NVARCHAR(100) NOT NULL,
    DiaChi NVARCHAR(255),
    SDT VARCHAR(15),
    TGMoCua TIME,
    TGDongCua TIME
);

CREATE TABLE DICH_VU (
    MaDV INT IDENTITY(1,1) PRIMARY KEY,
    LoaiDV NVARCHAR(100) NOT NULL,
    MoTa NVARCHAR(255)
);

CREATE TABLE DICH_VU_CUNG_CAP (
    MaCN INT,
    MaDV INT,
    TrangThai BIT DEFAULT 1,
    PRIMARY KEY (MaCN, MaDV),
    FOREIGN KEY (MaCN) REFERENCES CHI_NHANH(MaCN),
    FOREIGN KEY (MaDV) REFERENCES DICH_VU(MaDV)
);

CREATE TABLE GOI_TIEM (
    MaGoi INT IDENTITY(1,1) PRIMARY KEY,
    TenGoi NVARCHAR(100) NOT NULL,
    ThoiGian INT,
    -- RÀNG BUỘC: Ưu đãi từ 5% đến 15%
    UuDai INT CONSTRAINT CHK_UuDai_Range CHECK (UuDai >= 5 AND UuDai <= 15)
);

CREATE TABLE SAN_PHAM (
    MaSP INT IDENTITY(1,1) PRIMARY KEY,
    TenSP NVARCHAR(100) NOT NULL,
    LoaiSP NVARCHAR(50),
    GiaBan DECIMAL(18,0) NOT NULL CHECK (GiaBan >= 0),
    SoLuongTonKho INT DEFAULT 0 CHECK (SoLuongTonKho >= 0)
);

-----------------------------------------------------------
-- PHẦN 2: QUẢN LÝ NHÂN SỰ & KHÁCH HÀNG
-----------------------------------------------------------

CREATE TABLE NHAN_VIEN (
    MaNV INT IDENTITY(1,1) PRIMARY KEY,
    HoTen NVARCHAR(100) NOT NULL,
    NgaySinh DATE,
    GioiTinh NVARCHAR(10),
    SDT VARCHAR(15),
    NgayVaoLam DATE DEFAULT GETDATE(),
    LuongCoBan DECIMAL(18,0),
    ChucVu NVARCHAR(50) CHECK (ChucVu IN (N'Bác sĩ', N'Tiếp tân', N'Bán hàng', N'Quản lý')), 
    MaCN INT,
    FOREIGN KEY (MaCN) REFERENCES CHI_NHANH(MaCN)
);

CREATE TABLE LICH_SU_DIEU_DONG (
    MaDD INT IDENTITY(1,1) PRIMARY KEY,
    NgayChuyen DATE DEFAULT GETDATE(),
    MaNV INT,
    MaCN_Cu INT,
    MaCN_Moi INT,
    LyDo NVARCHAR(255),
    FOREIGN KEY (MaNV) REFERENCES NHAN_VIEN(MaNV),
    FOREIGN KEY (MaCN_Cu) REFERENCES CHI_NHANH(MaCN),
    FOREIGN KEY (MaCN_Moi) REFERENCES CHI_NHANH(MaCN)
);

CREATE TABLE KHACH_HANG (
    MaKH INT IDENTITY(1,1) PRIMARY KEY,
    TenKH NVARCHAR(100) NOT NULL,
    SDT VARCHAR(15) UNIQUE,
    Email VARCHAR(100),
    CCCD VARCHAR(20),
    GioiTinh NVARCHAR(10),
    NgaySinh DATE,
    DiemLoyalty INT DEFAULT 0,
    MaHang INT DEFAULT 1, 
    FOREIGN KEY (MaHang) REFERENCES HANG_THANH_VIEN(MaHang)
);

CREATE TABLE THU_CUNG (
    MaTC INT IDENTITY(1,1) PRIMARY KEY,
    TenTC NVARCHAR(50),
    Loai NVARCHAR(50),
    Giong NVARCHAR(50),
    -- RÀNG BUỘC: Ngày sinh nhỏ hơn hiện tại
    NgaySinh DATE CONSTRAINT CHK_NgaySinh_Pet CHECK (NgaySinh < GETDATE()),
    -- RÀNG BUỘC: Giới tính chuẩn
    GioiTinh NVARCHAR(10) CONSTRAINT CHK_GioiTinh_Pet CHECK (GioiTinh IN (N'Đực', N'Cái')),
    TinhTrangSucKhoe NVARCHAR(MAX),
    MaKH INT,
    FOREIGN KEY (MaKH) REFERENCES KHACH_HANG(MaKH)
);

-----------------------------------------------------------
-- PHẦN 3: GIAO DỊCH (HÓA ĐƠN & CHI TIẾT)
-----------------------------------------------------------

CREATE TABLE HOA_DON (
    MaHD INT IDENTITY(1,1) PRIMARY KEY,
    -- RÀNG BUỘC: Ngày lập <= hiện tại
    NgayLap DATETIME DEFAULT GETDATE() CONSTRAINT CHK_NgayLap_HD CHECK (NgayLap <= GETDATE()),
    -- RÀNG BUỘC: Tổng tiền >= 0
    TongTien DECIMAL(18,0) DEFAULT 0 CONSTRAINT CHK_TongTien_Min CHECK (TongTien >= 0),
    HinhThucThanhToan NVARCHAR(50),
    MaCN INT,
    MaKH INT,
    MaNV INT,
    FOREIGN KEY (MaCN) REFERENCES CHI_NHANH(MaCN),
    FOREIGN KEY (MaKH) REFERENCES KHACH_HANG(MaKH),
    FOREIGN KEY (MaNV) REFERENCES NHAN_VIEN(MaNV)
);

CREATE TABLE CT_HOA_DON_SP (
    MaHDSP INT IDENTITY(1,1) PRIMARY KEY,
    MaHD INT,
    MaSP INT,
    -- RÀNG BUỘC: Số lượng >= 1 và Đơn giá >= 0
    SoLuong INT CONSTRAINT CHK_SoLuong_Min CHECK (SoLuong >= 1),
    DonGia DECIMAL(18,0) CONSTRAINT CHK_DonGia_SP_Min CHECK (DonGia >= 0),
    ThanhTien AS (SoLuong * DonGia),
    FOREIGN KEY (MaHD) REFERENCES HOA_DON(MaHD),
    FOREIGN KEY (MaSP) REFERENCES SAN_PHAM(MaSP)
);

CREATE TABLE CT_HOA_DON_DV (
    MaHDDV INT IDENTITY(1,1) PRIMARY KEY,
    MaHD INT,
    MaDV INT NOT NULL,
    -- RÀNG BUỘC: Đơn giá >= 0
    DonGia DECIMAL(18,0) DEFAULT 0 CONSTRAINT CHK_DonGia_DV_Min CHECK (DonGia >= 0),
    FOREIGN KEY (MaHD) REFERENCES HOA_DON(MaHD),
    FOREIGN KEY (MaDV) REFERENCES DICH_VU(MaDV)
);

CREATE TABLE TT_KHAM_BENH (
    MaLanKham INT IDENTITY(1,1) PRIMARY KEY,
    MaHDDV INT UNIQUE,
    NgayKham DATETIME DEFAULT GETDATE(),
    TrieuChung NVARCHAR(MAX),
    ChuanDoan NVARCHAR(MAX),
    ToaThuoc NVARCHAR(MAX),
    NgayHenTaiKham DATE,
    MaTC INT,
    BSPhuTrach INT,
    FOREIGN KEY (MaHDDV) REFERENCES CT_HOA_DON_DV(MaHDDV),
    FOREIGN KEY (MaTC) REFERENCES THU_CUNG(MaTC),
    FOREIGN KEY (BSPhuTrach) REFERENCES NHAN_VIEN(MaNV)
);

CREATE TABLE TT_TIEM_PHONG (
    MaLanTiem INT IDENTITY(1,1) PRIMARY KEY,
    MaHDDV INT UNIQUE,
    NgayTiem DATETIME DEFAULT GETDATE(),
    LoaiVacXin NVARCHAR(100),
    LieuLuong NVARCHAR(50),
    MaGoi INT NULL,
    MaTC INT,
    NguoiTiem INT,
    FOREIGN KEY (MaHDDV) REFERENCES CT_HOA_DON_DV(MaHDDV),
    FOREIGN KEY (MaGoi) REFERENCES GOI_TIEM(MaGoi),
    FOREIGN KEY (MaTC) REFERENCES THU_CUNG(MaTC),
    FOREIGN KEY (NguoiTiem) REFERENCES NHAN_VIEN(MaNV)
);

CREATE TABLE DANH_GIA (
    MaDG INT IDENTITY(1,1) PRIMARY KEY,
    MaKH INT,
    MaCN INT,
    NgayDanhGia DATETIME DEFAULT GETDATE(),
    DiemChatLuongDV INT CHECK (DiemChatLuongDV BETWEEN 1 AND 5),
    DiemThaiDoNV INT CHECK (DiemThaiDoNV BETWEEN 1 AND 5),
    MDHaiLongTT INT CHECK (MDHaiLongTT BETWEEN 1 AND 5),
    BinhLuan NVARCHAR(MAX),
    FOREIGN KEY (MaKH) REFERENCES KHACH_HANG(MaKH),
    FOREIGN KEY (MaCN) REFERENCES CHI_NHANH(MaCN)
);
GO